# Generated by Django 4.0.1 on 2022-01-11 20:53

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=20),
        ),
    ]
