# Generated by Django 4.0.1 on 2022-01-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0003_alter_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postPhoto',
            field=models.FileField(default='uploads/3e5a955099.jpg', upload_to='uploads/'),
        ),
    ]
