# Generated by Django 4.0.1 on 2022-01-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0005_remove_post_postphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postPhoto',
            field=models.FileField(default='upload/photo_2021-11-18_20-35-02.jpg', upload_to='uploads/'),
        ),
    ]
