# Generated by Django 4.0.1 on 2022-01-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0006_post_postphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postPhoto',
            field=models.FileField(default=None, upload_to='uploads/'),
        ),
    ]
